### ISSUE TITLE
where is config file

### ISSUE THREAD

**Issue by modyamash** [SemperFortis/MEE7#2]
can you please update config file ? to we can test it?

**Comment by SemperFortis** [comment]
The config file (.env) holds the bot's private information and the only things that should be in there are TOKEN, PREFIX and any database variables. I will update a version with a sample of this soon but note a database is not provided and you must set that up yourself.

**Comment by SemperFortis** [comment]
A configuration file is now included, you need to rename .env_EXAMPLE to .env and fill out the proper environment variables.
